name: wf-assets
on:
  workflow_dispatch:

jobs:
  wf-assets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: eliyabot-assets
    - uses: actions/checkout@v4
      with:
        repository: blead/wf-assets
        path: wf-assets
        fetch-tags: true
    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.17.0'
    - name: Install jsonnet
      run: go install github.com/google/go-jsonnet/cmd/jsonnet@latest
    - name: Prepare directories
      run: mkdir -p ${GITHUB_WORKSPACE}/eliyabot-assets/output ${GITHUB_WORKSPACE}/eliyabot-assets/processed
    - name: Generate files
      run: jsonnet -m . -S main.jsonnet
      working-directory: ./eliyabot-assets
    - name: Get wf-assets version
      run: echo VERSION=$(git describe --tags --abbrev=0) >> ${GITHUB_ENV}
      working-directory: ./wf-assets
    - name: Git commit
      run: >
        git config user.name "wfax-bot" &&
        git config user.email "<>" &&
        git add . &&
        git commit -m "Automated update ${VERSION}" &&
        git tag "${VERSION}" &&
        git push origin master &&
        git push --tags --force origin ||
        true
      working-directory: ./eliyabot-assets
