name: wf-assets
on:
  workflow_dispatch:

jobs:
  wf-assets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: eliyabot-assets
    - uses: actions/checkout@v4
      with:
        repository: blead/wf-assets
        path: wf-assets
        fetch-tags: true
    - uses: actions/checkout@v4
      with:
        repository: poswords/EliyaBot
        path: EliyaBot
        sparse-checkout: |
          package.json
          parser.js
        sparse-checkout-cone-mode: false
    - uses: actions/setup-node@v3
      with:
        node-version-file: EliyaBot/package.json
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Apply parser.js.patch
      run: git apply ${GITHUB_WORKSPACE}/eliyabot-assets/.github/scripts/parser.js.patch
      working-directory: ./EliyaBot
    - name: Run parser.js
      run: >
        mv ${GITHUB_WORKSPACE}/EliyaBot/parser.js ${GITHUB_WORKSPACE}/parser.js &&
        mv ${GITHUB_WORKSPACE}/wf-assets/orderedmap ${GITHUB_WORKSPACE}/json &&
        mkdir ${GITHUB_WORKSPACE}/data && node ${GITHUB_WORKSPACE}/parser.js &&
        mv -f ${GITHUB_WORKSPACE}/data/* ${GITHUB_WORKSPACE}/eliyabot-assets/data
    - name: Run playable.py
      env:
        CHARS_JSON: eliyabot-assets/data/chars.json
        EQUIPS_JSON: eliyabot-assets/data/equips.json
        DEGREE_JSON: json/degree/degree.json
        PLAYABLE_CHARS_JSON: eliyabot-assets/processed/playable_chars.json
        PLAYABLE_EQUIPS_JSON: eliyabot-assets/processed/playable_equips.json
      run: python ${GITHUB_WORKSPACE}/eliyabot-assets/.github/scripts/playable.py
    - name: Run wfarea.py
      env:
        PLAYABLE_CHARS_JSON: eliyabot-assets/processed/playable_chars.json
        WFAREA_JSON: eliyabot-assets/processed/wfarea.json
      run: python ${GITHUB_WORKSPACE}/eliyabot-assets/.github/scripts/wfarea.py
    - name: Get wf-assets version
      run: echo VERSION=$(git describe --tags --abbrev=0) >> ${GITHUB_ENV}
      working-directory: ./wf-assets
    - name: Git commit
      run: >
        git config user.name "wfax-bot" &&
        git config user.email "<>" &&
        git add . &&
        git commit -m "Automated update ${VERSION}" &&
        git tag "${VERSION}" &&
        git push origin master &&
        git push --tags --force origin ||
        true
      working-directory: ./eliyabot-assets
